version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 3000
      runas: root
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 30000
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 3000
      runas: root
  ValidateService:
    - location: scripts/validate_server.sh
      timeout: 3000
      runas: root
